// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackChainSlopeUpSection01FormType), 1)]
public sealed class CoasterTrackChainSlopeUpSection04FormType:FormType { public override string Name=>"CoasterTrackChainSlopeUpSection04"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackChainSlopeUpSection04")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackChainSlopeUpSection04")); public override Type GroupType=>typeof(CoasterTrackChainGroup); public override int MinTier=>1; public override int SortOrder=>5; }
[RotatedVariants(typeof(CoasterTrackChainSlopeUpSection04R270Block),typeof(CoasterTrackChainSlopeUpSection04Block),typeof(CoasterTrackChainSlopeUpSection04R90Block),typeof(CoasterTrackChainSlopeUpSection04R180Block)),IsForm(typeof(CoasterTrackChainSlopeUpSection04FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSlopeUpSection04Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSlopeUpSection04R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSlopeUpSection04R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSlopeUpSection04R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
