// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackGradeUpSection01FormType), 1)]
public sealed class CoasterTrackGradeCompactUpEntrySection01FormType:FormType { public override string Name=>"CoasterTrackGradeCompactUpEntrySection01"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackGradeCompactUpEntrySection01")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackGradeCompactUpEntrySection01")); public override Type GroupType=>typeof(CoasterTrackSteepGroup); public override int MinTier=>1; public override int SortOrder=>5; }
[RotatedVariants(typeof(CoasterTrackGradeCompactUpEntrySection01R270Block),typeof(CoasterTrackGradeCompactUpEntrySection01Block),typeof(CoasterTrackGradeCompactUpEntrySection01R90Block),typeof(CoasterTrackGradeCompactUpEntrySection01R180Block)),IsForm(typeof(CoasterTrackGradeCompactUpEntrySection01FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeCompactUpEntrySection01Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeCompactUpEntrySection01R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeCompactUpEntrySection01R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeCompactUpEntrySection01R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
