// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackChainGradeUpEntrySection02FormType), 0)]
public sealed class CoasterTrackChainGradeUpEntrySection01FormType:FormType { public override string Name=>"CoasterTrackChainGradeUpEntrySection01"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackChainGradeUpEntrySection01")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackChainGradeUpEntrySection01")); public override Type GroupType=>typeof(CoasterTrackChainGroup); public override int MinTier=>1; public override int SortOrder=>20; }
[RotatedVariants(typeof(CoasterTrackChainGradeUpEntrySection01R270Block),typeof(CoasterTrackChainGradeUpEntrySection01Block),typeof(CoasterTrackChainGradeUpEntrySection01R90Block),typeof(CoasterTrackChainGradeUpEntrySection01R180Block)),IsForm(typeof(CoasterTrackChainGradeUpEntrySection01FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeUpEntrySection01Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeUpEntrySection01R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeUpEntrySection01R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeUpEntrySection01R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
