// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackChainSteepDownSection02FormType), 0)]
public sealed class CoasterTrackChainSteepDownSection01FormType:FormType { public override string Name=>"CoasterTrackChainSteepDownSection01"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackChainSteepDownSection01")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackChainSteepDownSection01")); public override Type GroupType=>typeof(CoasterTrackChainGroup); public override int MinTier=>1; public override int SortOrder=>12; }
[RotatedVariants(typeof(CoasterTrackChainSteepDownSection01R270Block),typeof(CoasterTrackChainSteepDownSection01Block),typeof(CoasterTrackChainSteepDownSection01R90Block),typeof(CoasterTrackChainSteepDownSection01R180Block)),IsForm(typeof(CoasterTrackChainSteepDownSection01FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSteepDownSection01Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSteepDownSection01R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSteepDownSection01R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSteepDownSection01R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
