// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackGradeDownSection01FormType), -1)]
public sealed class CoasterTrackGradeCompactCrestSection01FormType:FormType { public override string Name=>"CoasterTrackGradeCompactCrestSection01"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackGradeCompactCrestSection01")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackGradeCompactCrestSection01")); public override Type GroupType=>typeof(CoasterTrackSteepGroup); public override int MinTier=>1; public override int SortOrder=>9; }
[RotatedVariants(typeof(CoasterTrackGradeCompactCrestSection01R270Block),typeof(CoasterTrackGradeCompactCrestSection01Block),typeof(CoasterTrackGradeCompactCrestSection01R90Block),typeof(CoasterTrackGradeCompactCrestSection01R180Block)),IsForm(typeof(CoasterTrackGradeCompactCrestSection01FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeCompactCrestSection01Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeCompactCrestSection01R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeCompactCrestSection01R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeCompactCrestSection01R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
