// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackSlopeUpSection02FormType), 0)]
public sealed class CoasterTrackSlopeUpSection01FormType:FormType { public override string Name=>"CoasterTrackSlopeUpSection01"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackSlopeUpSection01")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackSlopeUpSection01")); public override Type GroupType=>typeof(CoasterTrackSlopeGroup); public override int MinTier=>1; public override int SortOrder=>1; }
[RotatedVariants(typeof(CoasterTrackSlopeUpSection01R270Block),typeof(CoasterTrackSlopeUpSection01Block),typeof(CoasterTrackSlopeUpSection01R90Block),typeof(CoasterTrackSlopeUpSection01R180Block)),IsForm(typeof(CoasterTrackSlopeUpSection01FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeUpSection01Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeUpSection01R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeUpSection01R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeUpSection01R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
