// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackChainGradeDownExitSection02FormType), 0)]
public sealed class CoasterTrackChainGradeDownExitSection01FormType:FormType { public override string Name=>"CoasterTrackChainGradeDownExitSection01"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackChainGradeDownExitSection01")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackChainGradeDownExitSection01")); public override Type GroupType=>typeof(CoasterTrackChainGroup); public override int MinTier=>1; public override int SortOrder=>22; }
[RotatedVariants(typeof(CoasterTrackChainGradeDownExitSection01R270Block),typeof(CoasterTrackChainGradeDownExitSection01Block),typeof(CoasterTrackChainGradeDownExitSection01R90Block),typeof(CoasterTrackChainGradeDownExitSection01R180Block)),IsForm(typeof(CoasterTrackChainGradeDownExitSection01FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeDownExitSection01Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeDownExitSection01R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeDownExitSection01R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeDownExitSection01R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
