// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackChainGradeDownSection01FormType), -1)]
public sealed class CoasterTrackChainGradeCompactDownEntrySection01FormType:FormType { public override string Name=>"CoasterTrackChainGradeCompactDownEntrySection01"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackChainGradeCompactDownEntrySection01")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackChainGradeCompactDownEntrySection01")); public override Type GroupType=>typeof(CoasterTrackChainGroup); public override int MinTier=>1; public override int SortOrder=>16; }
[RotatedVariants(typeof(CoasterTrackChainGradeCompactDownEntrySection01R270Block),typeof(CoasterTrackChainGradeCompactDownEntrySection01Block),typeof(CoasterTrackChainGradeCompactDownEntrySection01R90Block),typeof(CoasterTrackChainGradeCompactDownEntrySection01R180Block)),IsForm(typeof(CoasterTrackChainGradeCompactDownEntrySection01FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeCompactDownEntrySection01Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeCompactDownEntrySection01R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeCompactDownEntrySection01R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeCompactDownEntrySection01R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
