// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackChainGradeDownSection01FormType), -1)]
public sealed class CoasterTrackChainGradeDownEntrySection02FormType:FormType { public override string Name=>"CoasterTrackChainGradeDownEntrySection02"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackChainGradeDownEntrySection02")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackChainGradeDownEntrySection02")); public override Type GroupType=>typeof(CoasterTrackChainGroup); public override int MinTier=>1; public override int SortOrder=>26; }
[RotatedVariants(typeof(CoasterTrackChainGradeDownEntrySection02R270Block),typeof(CoasterTrackChainGradeDownEntrySection02Block),typeof(CoasterTrackChainGradeDownEntrySection02R90Block),typeof(CoasterTrackChainGradeDownEntrySection02R180Block)),IsForm(typeof(CoasterTrackChainGradeDownEntrySection02FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeDownEntrySection02Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeDownEntrySection02R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeDownEntrySection02R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeDownEntrySection02R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
