// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
public sealed class CoasterTrackSharpLeftSection01FormType:FormType { public override string Name=>"CoasterTrackSharpLeftSection01"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackSharpLeftSection01")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackSharpLeftSection01")); public override Type GroupType=>typeof(CoasterTrackBasicGroup); public override bool IsBottomHalfFill=>true; public override int MinTier=>1; public override int SortOrder=>2; }
[RotatedVariants(typeof(CoasterTrackSharpLeftSection01R270Block),typeof(CoasterTrackSharpLeftSection01Block),typeof(CoasterTrackSharpLeftSection01R90Block),typeof(CoasterTrackSharpLeftSection01R180Block)),IsForm(typeof(CoasterTrackSharpLeftSection01FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSharpLeftSection01Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSharpLeftSection01R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSharpLeftSection01R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSharpLeftSection01R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
