// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
public sealed class CoasterTrackBasicGroup:FormGroup { public override string Name=>"CoasterTrackBasicGroup"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Group("CoasterBasic")); public override LocString DisplayDescription=>Localizer.DoStr("Snap-together one-cell coaster shapes. Match numbered section sockets or combine them creatively."); public override int SortOrder=>110; }
