// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackSlopeDownSection01FormType), -1)]
public sealed class CoasterTrackSlopeDownSection04FormType:FormType { public override string Name=>"CoasterTrackSlopeDownSection04"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackSlopeDownSection04")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackSlopeDownSection04")); public override Type GroupType=>typeof(CoasterTrackSlopeGroup); public override int MinTier=>1; public override int SortOrder=>8; }
[RotatedVariants(typeof(CoasterTrackSlopeDownSection04R270Block),typeof(CoasterTrackSlopeDownSection04Block),typeof(CoasterTrackSlopeDownSection04R90Block),typeof(CoasterTrackSlopeDownSection04R180Block)),IsForm(typeof(CoasterTrackSlopeDownSection04FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeDownSection04Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeDownSection04R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeDownSection04R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeDownSection04R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
