// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackStraightSection01FormType), 0)]
public sealed class CoasterTrackGradeDownExitSection02FormType:FormType { public override string Name=>"CoasterTrackGradeDownExitSection02"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackGradeDownExitSection02")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackGradeDownExitSection02")); public override Type GroupType=>typeof(CoasterTrackSteepGroup); public override int MinTier=>1; public override int SortOrder=>14; }
[RotatedVariants(typeof(CoasterTrackGradeDownExitSection02R270Block),typeof(CoasterTrackGradeDownExitSection02Block),typeof(CoasterTrackGradeDownExitSection02R90Block),typeof(CoasterTrackGradeDownExitSection02R180Block)),IsForm(typeof(CoasterTrackGradeDownExitSection02FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeDownExitSection02Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeDownExitSection02R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeDownExitSection02R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeDownExitSection02R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
