// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackSlopeDownSection04FormType), 0)]
public sealed class CoasterTrackSlopeDownSection03FormType:FormType { public override string Name=>"CoasterTrackSlopeDownSection03"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackSlopeDownSection03")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackSlopeDownSection03")); public override Type GroupType=>typeof(CoasterTrackSlopeGroup); public override int MinTier=>1; public override int SortOrder=>7; }
[RotatedVariants(typeof(CoasterTrackSlopeDownSection03R270Block),typeof(CoasterTrackSlopeDownSection03Block),typeof(CoasterTrackSlopeDownSection03R90Block),typeof(CoasterTrackSlopeDownSection03R180Block)),IsForm(typeof(CoasterTrackSlopeDownSection03FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeDownSection03Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeDownSection03R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeDownSection03R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeDownSection03R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
