// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackChainGradeUpSection01FormType), 1)]
public sealed class CoasterTrackChainGradeCompactDipSection01FormType:FormType { public override string Name=>"CoasterTrackChainGradeCompactDipSection01"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackChainGradeCompactDipSection01")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackChainGradeCompactDipSection01")); public override Type GroupType=>typeof(CoasterTrackChainGroup); public override int MinTier=>1; public override int SortOrder=>19; }
[RotatedVariants(typeof(CoasterTrackChainGradeCompactDipSection01R270Block),typeof(CoasterTrackChainGradeCompactDipSection01Block),typeof(CoasterTrackChainGradeCompactDipSection01R90Block),typeof(CoasterTrackChainGradeCompactDipSection01R180Block)),IsForm(typeof(CoasterTrackChainGradeCompactDipSection01FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeCompactDipSection01Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeCompactDipSection01R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeCompactDipSection01R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeCompactDipSection01R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
