// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackSlopeUpSection01FormType), 1)]
public sealed class CoasterTrackSlopeUpSection04FormType:FormType { public override string Name=>"CoasterTrackSlopeUpSection04"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackSlopeUpSection04")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackSlopeUpSection04")); public override Type GroupType=>typeof(CoasterTrackSlopeGroup); public override int MinTier=>1; public override int SortOrder=>4; }
[RotatedVariants(typeof(CoasterTrackSlopeUpSection04R270Block),typeof(CoasterTrackSlopeUpSection04Block),typeof(CoasterTrackSlopeUpSection04R90Block),typeof(CoasterTrackSlopeUpSection04R180Block)),IsForm(typeof(CoasterTrackSlopeUpSection04FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeUpSection04Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeUpSection04R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeUpSection04R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeUpSection04R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
