// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackStraightSection01FormType), 1)]
public sealed class CoasterTrackGradeCompactUpExitSection01FormType:FormType { public override string Name=>"CoasterTrackGradeCompactUpExitSection01"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackGradeCompactUpExitSection01")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackGradeCompactUpExitSection01")); public override Type GroupType=>typeof(CoasterTrackSteepGroup); public override int MinTier=>1; public override int SortOrder=>6; }
[RotatedVariants(typeof(CoasterTrackGradeCompactUpExitSection01R270Block),typeof(CoasterTrackGradeCompactUpExitSection01Block),typeof(CoasterTrackGradeCompactUpExitSection01R90Block),typeof(CoasterTrackGradeCompactUpExitSection01R180Block)),IsForm(typeof(CoasterTrackGradeCompactUpExitSection01FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeCompactUpExitSection01Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeCompactUpExitSection01R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeCompactUpExitSection01R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackGradeCompactUpExitSection01R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
