// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackSlopeDownSection02FormType), 0)]
public sealed class CoasterTrackSlopeDownSection01FormType:FormType { public override string Name=>"CoasterTrackSlopeDownSection01"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackSlopeDownSection01")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackSlopeDownSection01")); public override Type GroupType=>typeof(CoasterTrackSlopeGroup); public override int MinTier=>1; public override int SortOrder=>5; }
[RotatedVariants(typeof(CoasterTrackSlopeDownSection01R270Block),typeof(CoasterTrackSlopeDownSection01Block),typeof(CoasterTrackSlopeDownSection01R90Block),typeof(CoasterTrackSlopeDownSection01R180Block)),IsForm(typeof(CoasterTrackSlopeDownSection01FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeDownSection01Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeDownSection01R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeDownSection01R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackSlopeDownSection01R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
