// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackChainStraightSection01FormType), 1)]
public sealed class CoasterTrackChainGradeCompactUpExitSection01FormType:FormType { public override string Name=>"CoasterTrackChainGradeCompactUpExitSection01"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackChainGradeCompactUpExitSection01")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackChainGradeCompactUpExitSection01")); public override Type GroupType=>typeof(CoasterTrackChainGroup); public override int MinTier=>1; public override int SortOrder=>15; }
[RotatedVariants(typeof(CoasterTrackChainGradeCompactUpExitSection01R270Block),typeof(CoasterTrackChainGradeCompactUpExitSection01Block),typeof(CoasterTrackChainGradeCompactUpExitSection01R90Block),typeof(CoasterTrackChainGradeCompactUpExitSection01R180Block)),IsForm(typeof(CoasterTrackChainGradeCompactUpExitSection01FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeCompactUpExitSection01Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeCompactUpExitSection01R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeCompactUpExitSection01R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainGradeCompactUpExitSection01R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
