// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackChainSlopeDownSection04FormType), 0)]
public sealed class CoasterTrackChainSlopeDownSection03FormType:FormType { public override string Name=>"CoasterTrackChainSlopeDownSection03"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackChainSlopeDownSection03")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackChainSlopeDownSection03")); public override Type GroupType=>typeof(CoasterTrackChainGroup); public override int MinTier=>1; public override int SortOrder=>8; }
[RotatedVariants(typeof(CoasterTrackChainSlopeDownSection03R270Block),typeof(CoasterTrackChainSlopeDownSection03Block),typeof(CoasterTrackChainSlopeDownSection03R90Block),typeof(CoasterTrackChainSlopeDownSection03R180Block)),IsForm(typeof(CoasterTrackChainSlopeDownSection03FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSlopeDownSection03Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSlopeDownSection03R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSlopeDownSection03R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSlopeDownSection03R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
