// Generated by tools/Generate-CoasterForms.ps1 from the shared physics catalogue.
namespace Eco.Mods.TechTree;
using Eco.Core.Items;
using Eco.Gameplay.Blocks;
using Eco.Gameplay.Objects;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using Eco.Shared.SharedTypes;
using Eco.World.Blocks;
using Eco.World.Water;
[NextRamp(typeof(CoasterTrackChainSlopeUpSection02FormType), 0)]
public sealed class CoasterTrackChainSlopeUpSection01FormType:FormType { public override string Name=>"CoasterTrackChainSlopeUpSection01"; public override LocString DisplayName=>Localizer.DoStr(CoasterTrackNames.Name("CoasterTrackChainSlopeUpSection01")); public override LocString DisplayDescription=>Localizer.DoStr(CoasterTrackNames.Description("CoasterTrackChainSlopeUpSection01")); public override Type GroupType=>typeof(CoasterTrackChainGroup); public override int MinTier=>1; public override int SortOrder=>2; }
[RotatedVariants(typeof(CoasterTrackChainSlopeUpSection01R270Block),typeof(CoasterTrackChainSlopeUpSection01Block),typeof(CoasterTrackChainSlopeUpSection01R90Block),typeof(CoasterTrackChainSlopeUpSection01R180Block)),IsForm(typeof(CoasterTrackChainSlopeUpSection01FormType),typeof(CoasterTrackItem))]
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSlopeUpSection01Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSlopeUpSection01R90Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSlopeUpSection01R180Block:CoasterTrackBlock,IWaterLoggedBlock{}
[Serialized,Constructed,Solid,BlockTier(1),Tag("Constructable")]
public sealed class CoasterTrackChainSlopeUpSection01R270Block:CoasterTrackBlock,IWaterLoggedBlock{}
