using UnityEngine;

// Serialization-only mirror of the installed ThirdParty RCC controller.
// Eco supplies its compiled runtime implementation when loading the bundle.
public class RCCCarControllerV2 : MonoBehaviour
{
    public bool mobileController = false;
    public int _mobileControllerType = 0;
    public bool AIController = false;
    public bool dashBoard = false;
    public int _dashboardType = 0;
    public bool useAccelerometerForSteer = false;
    public bool steeringWheelControl = false;
    public float gyroTiltMultiplier = 2f;
    public bool demoGUI = false;
    public bool showMobileControllerChangerButtons = false;
    public bool autoFindButtons = false;
    public UnityEngine.Object gasPedalNGUI;
    public UnityEngine.Object brakePedalNGUI;
    public UnityEngine.Object leftArrowNGUI;
    public UnityEngine.Object rightArrowNGUI;
    public UnityEngine.Object handbrakeNGUI;
    public UnityEngine.Object boostNGUI;
    public UnityEngine.Object gasPedalUI;
    public UnityEngine.Object brakePedalUI;
    public UnityEngine.Object leftArrowUI;
    public UnityEngine.Object rightArrowUI;
    public UnityEngine.Object handbrakeUI;
    public UnityEngine.Object boostUI;
    public Transform FrontLeftWheelTransform;
    public Transform FrontRightWheelTransform;
    public Transform RearLeftWheelTransform;
    public Transform RearRightWheelTransform;
    public bool threeWheelSteering = false;
    public bool syncWheelPositions = false;
    public Quaternion steeringRotation = Quaternion.identity;
    public float steeringRotationRatio = 1f;
    public float steeringRotationSpeed = 1f;
    public WheelCollider FrontLeftWheelCollider;
    public WheelCollider FrontRightWheelCollider;
    public WheelCollider RearLeftWheelCollider;
    public WheelCollider RearRightWheelCollider;
    public WheelCollider[] allWheelColliders = new WheelCollider[0];
    public Transform[] ExtraRearWheelsTransform = new Transform[0];
    public WheelCollider[] ExtraRearWheelsCollider = new WheelCollider[0];
    public bool applyEngineTorqueToExtraRearWheelColliders = true;
    public Transform SteeringWheel;
    public int _wheelTypeChoise = 0;
    public Transform COM;
    public bool canControl = false;
    public bool runEngineAtAwake = false;
    public bool canEngineStall = false;
    public bool engineRunning = false;
    public bool autoReverse = true;
    public bool automaticGear = true;
    public bool isAutoMoving = false;
    public AnimationCurve[] engineTorqueCurve = new AnimationCurve[0];
    public float[] gearSpeed = new float[0];
    public float engineTorque = 5500f;
    public float maxEngineRPM = 8000f;
    public float minEngineRPM = 1000f;
    public bool footPoweredCart = true;
    public bool invertCartSteer = false;
    public float steerAngle = 180f;
    public float highspeedsteerAngle = 180f;
    public float highspeedsteerAngleAtspeed = 80f;
    public float antiRoll = 2500f;
    public float downForce = 25f;
    public float speed = 0f;
    public float brake = 5000f;
    public float maxspeed = 30f;
    public float maxAngularSpeed = 12f;
    public int currentGear = 0;
    public int totalGears = 1;
    public float gearShiftingDelay = 0f;
    public bool changingGear = false;
    public bool reverseGear = false;
    public bool autoGenerateGearCurves = true;
    public bool autoGenerateTargetSpeedsForChangingGear = true;
    public AudioClip engineStartClip;
    public AudioClip engineClipOn;
    public AudioClip engineClipOff;
    public UnityEngine.Object engineMixer;
    public AudioClip[] gearShiftingClips = new AudioClip[0];
    public AudioClip[] crashClips = new AudioClip[0];
    public AudioClip windClip;
    public UnityEngine.Object windMixer;
    public AudioClip brakeClip;
    public AudioClip asphaltSkidClip;
    public AudioClip grassSkidClip;
    public AudioClip sandSkidClip;
    public float minEngineSoundPitch = 0.75f;
    public float maxEngineSoundPitch = 2f;
    public float minEngineSoundVolume = 0.05000000074505806f;
    public float maxEngineSoundVolume = 0.8500000238418579f;
    public float engineStartVolume = 0.05000000074505806f;
    public float maxGearShiftingSoundVolume = 0.30000001192092896f;
    public float maxSkidSoundVolume = 1f;
    public float maxCrashSoundVolume = 1f;
    public float maxWindSoundVolume = 0.25f;
    public float maxBrakeSoundVolume = 0.25f;
    public PhysicsMaterial asphaltPhysicsMaterial;
    public PhysicsMaterial grassPhysicsMaterial;
    public PhysicsMaterial sandPhysicsMaterial;
    public PhysicsMaterial terrainPhysicsMaterial;
    public bool UseTerrainSplatMapForGroundPhysics = true;
    public int terrainSplatMapAsphaltIndex = 1;
    public int terrainSplatMapGrassIndex = 0;
    public int terrainSplatMapSandIndex = 2;
    public float gasInput = 0f;
    public float brakeInput = 0f;
    public float steerInput = 0f;
    public float clutchInput = 0f;
    public float handbrakeInput = 0f;
    public float fuelInput = 1f;
    public float boostInput = 1f;
    public UnityEngine.Object UIInputs;
    public GameObject RPMNeedleNGUI;
    public GameObject KMHNeedleNGUI;
    public int _groundMaterial = 0;
    public GameObject wheelSlipAsphalt;
    public GameObject wheelSlipSand;
    public ParticleSystem[] exhaustGas = new ParticleSystem[0];
    public GameObject chassis;
    public float chassisVerticalLean = 4f;
    public float chassisHorizontalLean = 4f;
    public Light[] headLights = new Light[0];
    public Light[] brakeLights = new Light[0];
    public Light[] reverseLights = new Light[0];
    public bool headLightsOn = false;
    public bool useDamage = false;
    public MeshFilter[] deformableMeshFilters = new MeshFilter[0];
    public float randomizeVertices = 1f;
    public float damageRadius = 0.5f;
    public bool sleep = true;
    public float maximumDamage = 0.5f;
    public float damageMultiplier = 1f;
    public GameObject contactSparkle;
    public int maximumContactSparkle = 5;
    public bool repairNow = false;
    public float steerHelper = 0.10000000149011612f;
    public bool ABS = true;
    public bool TCS = true;
    public bool ESP = true;
    public bool steeringHelper = true;
    public bool ABSAct = false;
    public bool TCSAct = false;
    public bool ESPAct = false;
    public float ABSThreshold = 0.3499999940395355f;
    public float TCSThreshold = 0.25f;
    public float TCSStrength = 1f;
    public float ESPThreshold = 0.25f;
    public float ESPStrength = 0.25f;
    public bool applyCounterSteering = true;
    public GameObject steeringWheelGameObject;
    public UnityEngine.Object steeringWheelTexture;
    public float steeringWheelAngle = 0f;
    public float steeringWheelMaximumsteerAngle = 270f;
    public float steeringWheelResetPosSpeed = 15f;
    public float steeringWheelCenterDeadZoneRadius = 5f;
    public float steeringWheelDefaultAlpha = 0.5f;
    public float steeringWheelActiveAlpha = 1f;
    public bool steeringWheelInteractable = true;
    public bool autoBrakeWhenNotUsingGas = true;
    public float reverseBrakeSpeed = 2f;
}
