<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Eco.Railcraft.CoasterCamera.Client</AssemblyName>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <Version>0.2.67</Version>
    <ClientRoot Condition="'$(ClientRoot)' == ''">G:/SteamLibrary/steamapps/common/Eco</ClientRoot>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx.Core"><HintPath>$(ClientRoot)/BepInEx/core/BepInEx.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx.Unity.IL2CPP"><HintPath>$(ClientRoot)/BepInEx/core/BepInEx.Unity.IL2CPP.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppInterop.Runtime"><HintPath>$(ClientRoot)/BepInEx/core/Il2CppInterop.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(ClientRoot)/BepInEx/core/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="$(ClientRoot)/BepInEx/interop/*.dll"><Private>false</Private></Reference>
  </ItemGroup>
</Project>
